version: '3.2'
services:
  bot:
    image: senre/yellow-rs
    container_name: yellow-rs
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:postgres
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data
volumes:
  database-data:
